name: server
description: A web server without any additional dependencies.
# version: 1.0.0
# homepage: https://www.example.com
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^1.4.0
