name: models
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^1.4.0